//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSqlAzManWCFServiceWinTest.NetSqlAzManSR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SqlAzManStorage", Namespace="http://NetSqlAzMan/ServiceModel", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SqlAzManStorage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NetSqlAzManSR.INetSqlAzManWCFService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface INetSqlAzManWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetSqlAzManWCFService/CreateStorageInstance", ReplyAction="http://tempuri.org/INetSqlAzManWCFService/CreateStorageInstanceResponse")]
        NetSqlAzManWCFServiceWinTest.NetSqlAzManSR.SqlAzManStorage CreateStorageInstance(string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INetSqlAzManWCFServiceChannel : NetSqlAzManWCFServiceWinTest.NetSqlAzManSR.INetSqlAzManWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetSqlAzManWCFServiceClient : System.ServiceModel.ClientBase<NetSqlAzManWCFServiceWinTest.NetSqlAzManSR.INetSqlAzManWCFService>, NetSqlAzManWCFServiceWinTest.NetSqlAzManSR.INetSqlAzManWCFService {
        
        public NetSqlAzManWCFServiceClient() {
        }
        
        public NetSqlAzManWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NetSqlAzManWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetSqlAzManWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetSqlAzManWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NetSqlAzManWCFServiceWinTest.NetSqlAzManSR.SqlAzManStorage CreateStorageInstance(string connectionString) {
            return base.Channel.CreateStorageInstance(connectionString);
        }
    }
}
